### ISSUE TITLE
Add page or pages on Cloud-Optimized Point Clouds (COPC)

### ISSUE THREAD

**Issue by abarciauskas-bgse** [developmentseed/cloud-optimized-geospatial-formats-guide#11]
- [ ] A single page describing the basics of that format.
- [ ] An example creating a file of the format (could be merged with the format description).
- [ ] An example of a cloud optimized access of the file (could be merged with pages above).
- Links to relevant references

Optional:
* Tradeoffs and alternatives to consider when using this format

Considerations
* If a subpage is required, then convert that entry to a subfolder of the format.

**Comment by wildintellect** [comment]
Basic ideas:
- Use COPC when you have LiDAR or LiDAR like data (dense 3d data, what qualifies as dense is up for debate)
- Spatial Index is 3D X, Y and Z
- Compressed - just skip past LAS straight to LAZ, and if you're doing LAZ, no loss to do COPC
- Requires PDAL
